import React from 'react';
import { Page, View, Text, StyleSheet } from '@react-pdf/renderer';
import { S, COLORS } from '../pdfStyles';

const styles = StyleSheet.create({
  page: { fontFamily: 'Helvetica', backgroundColor: COLORS.slate50, padding: 0 },
  body: { padding: 36 },
  heading: { fontSize: 18, fontFamily: 'Helvetica-Bold', color: COLORS.slate900, marginBottom: 6 },
  sub: { fontSize: 9.5, color: COLORS.slate600, lineHeight: 1.75, marginBottom: 16 },
  methodBox: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.slate200,
    borderRadius: 10,
    padding: 14,
    marginBottom: 12,
  },
  methodTitle: { fontSize: 9, fontFamily: 'Helvetica-Bold', color: COLORS.slate900, marginBottom: 5 },
  methodBody: { fontSize: 8.5, color: COLORS.slate600, lineHeight: 1.7 },
  legalBox: {
    backgroundColor: COLORS.slate900,
    borderRadius: 10,
    padding: 16,
    marginTop: 16,
  },
  legalTitle: { fontSize: 8, fontFamily: 'Helvetica-Bold', color: COLORS.emerald500, letterSpacing: 2, textTransform: 'uppercase', marginBottom: 8 },
  legalText: { fontSize: 8, color: COLORS.slate400, lineHeight: 1.8 },
});

function PageHeader({ date }) {
  return (
    <View style={S.pageHeader}>
      <View style={S.brandRow}><View style={S.brandDot} /><Text style={S.brandName}>Terra AI · Methodology & Legal Disclaimers</Text></View>
      <Text style={S.headerRight}>{date}</Text>
    </View>
  );
}

export default function DisclaimerPage({ report, date }) {
  const customDisclaimer = report?.disclaimer;

  return (
    <Page size="A4" style={styles.page}>
      <PageHeader date={date} />
      <View style={styles.body}>
        <Text style={styles.heading}>Methodology & Data Sources</Text>
        <Text style={styles.sub}>
          This report is generated by the Terra AI Geospatial Intelligence Engine, which orchestrates
          multiple independent data sources and AI systems to produce a comprehensive land risk assessment.
        </Text>

        {[
          {
            title: 'Elevation & Slope — Google Maps Elevation API',
            body: 'Terrain elevation is queried via the Google Maps Elevation API at the exact dropped-pin coordinate. Slope percentage is derived from multi-point sampling within a 50m radius. Accuracy is typically ±5m for altitude and ±2% for slope on standard terrain.',
          },
          {
            title: 'Infrastructure Proximity — OpenStreetMap (Overpass API)',
            body: 'Distances to roads, waterways, power lines, schools, markets, and other features are computed by querying the OpenStreetMap Overpass API within a 2km radius, then calculating Euclidean distance via the Shapely geometry engine. OSM data quality varies by region; urban areas across Kenya are typically well-mapped.',
          },
          {
            title: 'Flood & Land Cover — Google Earth Engine (JRC / Dynamic World)',
            body: 'Historical flood extent is derived from the JRC (Joint Research Centre) Global Surface Water dataset via the Earth Engine REST API. Vegetation NDVI, land cover classification, and seasonal water presence are derived from the Dynamic World v1 dataset (Sentinel-2 imagery, 10m resolution).',
          },
          {
            title: 'Soil Classification — ISRIC SoilGrids v2.0',
            body: 'Clay content, CEC (Cation Exchange Capacity), silt, and bulk density at 30–60 cm depth are fetched from the ISRIC SoilGrids public REST API (rest.isric.org). Values are used to classify foundation risk: Black Cotton Clay (clay >45% + CEC >30 cmol/kg), Moderate Clay/Loam (30–45%), or Stable/Red Laterite (<30%). No API key required.',
          },
          {
            title: 'Solar Potential — Google Solar API',
            body: 'Solar data is sourced from the Google Solar API buildingInsights endpoint. If no building-level data is available, the Kenya equatorial standard of 5.5 peak sun hours/day is applied (equivalent to ~2,007 annual sunshine hours).',
          },
          {
            title: 'AI Risk Synthesis — Google Gemini 2.5 Flash',
            body: 'The final risk narrative, section analysis, investment verdict, and financial synthesis are generated by Gemini 2.5 Flash, prompted with the full payload of geospatial data. In the event of API failure, a deterministic fallback report is generated server-side.',
          },
          {
            title: 'Legal Risk Engine — Shapely Geometry + HydroSHEDS',
            body: 'Riparian buffer compliance (30m rule under EMCA), road reserve overlap, and aviation zone analysis are computed by the Shapely planar geometry engine against OpenStreetMap feature polygons, continent-wide HydroSHEDS rivers, and known major airport coordinates for Kenya.',
          },
        ].map(({ title, body }) => (
          <View key={title} style={styles.methodBox}>
            <Text style={styles.methodTitle}>{title}</Text>
            <Text style={styles.methodBody}>{body}</Text>
          </View>
        ))}

        <View style={styles.legalBox}>
          <Text style={styles.legalTitle}>Legal Disclaimer</Text>
          <Text style={styles.legalText}>
            {customDisclaimer ? `${customDisclaimer}\n\n` : ''}
            Geospatial data derived from ISRIC SoilGrids, HydroSHEDS, and Google Earth Engine. This exploratory report does not replace an official Ministry of Lands physical survey or NEMA assessment.

            This report is generated via geospatial AI for exploratory due diligence purposes only. It does NOT replace an official Ministry of Lands physical survey, a NEMA (National Environment Management Authority) environmental assessment, or any other statutory land evaluation. The risk scores, distances, and financial estimates herein are probabilistic indicators derived from public data sources and AI modelling — they are NOT ground-truthed legal or engineering opinions.{'\n\n'}
            Terra AI Ltd accepts no liability for any decisions, financial commitments, or legal actions taken solely on
            the basis of this report. Before any purchase, transfer, or development, clients are advised to commission a
            licensed surveyor, conduct a formal title search at the Ministry of Lands, and consult a qualified legal
            professional and structural engineer.{'\n\n'}
            All data is sourced from publicly available APIs (OpenStreetMap, Google Maps, Open-Meteo, Google Earth Engine)
            under their respective terms of service. Data quality, accuracy, and coverage vary by location.
          </Text>
        </View>
      </View>
    </Page>
  );
}
